name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Cache .NET
        uses: actions/cache@v4
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('global.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'
      - name: Install iOS workload
        run: dotnet workload install maui-ios
      - name: Build
        run: dotnet build -c Release
